/**
 * Users setting for testing this app.
 * Includes apiKey, api secret key generated by dev.twitter.com for the use of this app.
 * access Token with read/write permission for testing. Currently for my account (GBenbenisti).
  * @type {{keysAndTokens: {apiKey: string, apiSecretKey: string, accessToken: string, accessTokenSecret: string}}}
 */
module.exports = {
    keysAndTokens : {
        consumer_key: 'shEgjqTxykO2a9eC0T58P4oGY',
        consumer_secret: 'LAAPDVeWMOYME3UF8VTn94ZTNTc1NdgHRnkfP0RxPMH3oneOHx',
        access_token_key: '1087698727555473408-LPS0WHccQJpoelaUspN9iWjO83URL5',
        access_token_secret: 'x03kfkoNEEXrT4Y2g6Wi8A5gmgTBfKGgcjszI6KvwSW71'
    }
}